### ISSUE TITLE
[191214] mission001

### ISSUE THREAD

**Issue by eastjun-dev** [EastjunDev/frontend#1]
<br>
<p align="middle" >
  <img src="https://user-images.githubusercontent.com/50367798/61579463-568f4f80-ab40-11e9-8b34-5ca76a61de8b.gif"/>
</p>

<p align="middle">
  <img src="https://img.shields.io/badge/version-0.0.1-blue?style=flat-square" alt="template version"/>
<img src="https://img.shields.io/badge/language-javascript-%23f8df17"/>
<a href="https://github.com/daybrush/moveable/blob/master/LICENSE" target="_blank">
  <img src="https://img.shields.io/github/license/daybrush/moveable.svg?style=flat-square&label=license&color=08CE5D"/>
  </a>
</p>

<br>

## 🔥 TODOS 시스템의 CRUD를 구현하기

이 템플릿은 vanilla javascript를 학습을 위한 todos template입니다.  
이 template은 [링크](https://github.com/tastejs/todomvc)의 저장소에서 클론하여 필요한 부분만 사용하였습니다.   
이번 미션에서 우리는 기존에 학습 했던 내용들을 복습하며 todo list를 다시 만들어보는 작업을 진행할 예정입니다.
요구사항은 아래와 같습니다.

<br>

## 🏴 Missions
- [ ] todo list에 todoItem을 키보드로 입력하여 추가
- [ ] todo list의 체크박스를 클릭하여 complete 상태로 변경. (li tag 에 completed class 추가)
- [ ] todo list의 x버튼을 이용해서 해당 엘리먼트를 삭제
- [ ]  todo list를 더블클릭했을 때 input 모드로 변경. (li tag 에 editing class 추가) 단 이때 수정을 완료하지 않은 상태에서 esc키를 누르면 수정되지 않은 채로 다시 view 모드로 복귀
- [ ] todo list의 item갯수를 count한 갯수를 리스트의 하단에 보여주기
- [ ] todo list의 상태값을 확인하여, 해야할 일과, 완료한 일을 클릭하면 해당 상태의 아이템만 보여주기

<br>

### @eastjun 
> @YongHoonJJo @StellaKim1230  @ganeodolu 
<br>

### @YongHoonJJo 
> @eastjun  @StellaKim1230  @s280493 
<br>

### @StellaKim1230 
> @eastjun @ganeodolu  @s280493 
<br>

### @ganeodolu 
> @eastjun @s280493  @YongHoonJJo 
<br>

### @s280493 
> @YongHoonJJo @StellaKim1230 @ganeodolu 
<br>

### @amorfati0310 
> @eastjun @YongHoonJJo @StellaKim1230
<br>

### @HoseokNa 
> @eastjun @ganeodolu @amorfati0310
